// https://github.com/xoofx/SharpNng/blob/main/src/SharpNng.CodeGen/Program.cs
// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.
using System;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

using CppAst;
using CppAst.CodeGen.Common;
using CppAst.CodeGen.CSharp;

using Zio.FileSystems;

namespace Nnng.CodeGen;

internal class Program
{
    static int Main(string[] args)
    {
        var thisFilePath = GetThisFilePath();
        var thisFileDirectory = Path.GetDirectoryName(thisFilePath);

        var nngIncludeDirectory = Path.Combine(
            thisFileDirectory,
            "nng",
            "include");
        if (!Directory.Exists(nngIncludeDirectory))
        {
            Console.Error.WriteLine($"The nng include directory `{nngIncludeDirectory}` doesn't exist.");
            return 1;
        }

        var targetDirectory = Path.Combine(
            thisFileDirectory,
            "..",
            "Nnng",
            "Interop");
        if (!Directory.Exists(targetDirectory))
            Directory.CreateDirectory(targetDirectory);

        var csOptions = new CSharpConverterOptions
        {
            AllowFixedSizeBuffers = true,
            DefaultClassLib = "NngNative",
            DefaultDllImportNameAndArguments = "\"nng\"",
            DefaultMarshalForString = new CSharpMarshalAsAttribute(UnmanagedType.LPStr),
            DefaultNamespace = "Nnng.Interop",
            DefaultOutputFilePath = "NngNative.g.cs",
            Defines =
            {
                "NNG_ELIDE_DEPRECATED",
            },
            //DetectOpaquePointers = false,
            //DispatchOutputPerInclude = true,
            DisableRuntimeMarshalling = false,
            DisableTypedefToStructWrap = true,
            GenerateEnumItemAsFields = false,
            //MappingRules =
            //{
            //    e => e.MapType("nng_msg *", "System.IntPtr"),
            //},
            ParserKind = CppParserKind.Cpp,
            TypedefCodeGenKind = CppTypedefCodeGenKind.NoWrap,
            UseLibraryImport = false,
        };
        csOptions.IncludeFolders.Add(nngIncludeDirectory);

        var nngHeaderFiles = Directory.GetFiles(
            nngIncludeDirectory,
            "*.h",
            SearchOption.AllDirectories)
            .ToList();

        var csCompilation = CSharpConverter.Convert(nngHeaderFiles, csOptions);
        if (csCompilation.HasErrors)
        {
            Console.Error.WriteLine("Unexpected parsing errors:");
            foreach (var message in csCompilation.Diagnostics.Messages)
                Console.Error.WriteLine(message);

            return 2;
        }

        // Move using declarations out of namespace to file level
        var csFile = csCompilation.Members.OfType<CSharpGeneratedFile>().First();
        var csNamespace = csFile.Members.OfType<CSharpNamespace>().FirstOrDefault();
        if (csNamespace != null)
        {
            var usings = csNamespace.Members.OfType<CSharpUsingDeclaration>().ToList();
            foreach (var use in usings)
                csNamespace.Members.Remove(use);

            var nsIndex = csFile.Members.IndexOf(csNamespace);
            for (int i = 0; i < usings.Count; i++)
                csFile.Members.Insert(nsIndex + i, usings[i]);
        }

        // Replace nint with IntPtr in opaque struct members
        if (csNamespace != null)
        {
            foreach (var csClass in csNamespace.Members.OfType<CSharpClass>())
            {
                foreach (var csStruct in csClass.Members.OfType<CSharpStruct>())
                {
                    foreach (var lineElement in csStruct.Members.OfType<CSharpLineElement>())
                    {
                        var originalText = lineElement.Text;
                        lineElement.Text = () => originalText().Replace("nint", "IntPtr");
                    }
                }
            }
        }

        // Write generated file back to disk
        var fileSystem = new PhysicalFileSystem();
        var subFileSystem = new SubFileSystem(fileSystem, fileSystem.ConvertPathFromInternal(targetDirectory));
        var codeWriterOptions = new CodeWriterOptions(subFileSystem)
        {
            //DefaultUsings = [
            //    "using System;",
            //    "using System.Runtime.CompilerServices;",
            //    "using System.Runtime.InteropServices;",
            //],
            Header = $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Nnng.CodeGen.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591",
        };
        var codeWriter = new CodeWriter(codeWriterOptions);
        csCompilation.DumpTo(codeWriter);

        return 0;
    }

    private static string GetThisFilePath([CallerFilePath] string path = null) => path;
}


// References:
// [How do I get the path to the current C# source code file?](https://stackoverflow.com/questions/47841441/how-do-i-get-the-path-to-the-current-c-sharp-source-code-file)
// [NoWrap questions](https://github.com/xoofx/CppAst.CodeGen/issues/37)
